// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLNLP-antR76LPUGnLfoGPnniWfeQ0UkQ',
    appId: '1:314765251666:web:2f197a29916d6883947b8b',
    messagingSenderId: '314765251666',
    projectId: 'goldcalculator-42271',
    authDomain: 'goldcalculator-42271.firebaseapp.com',
    databaseURL: 'https://goldcalculator-42271.firebaseio.com',
    storageBucket: 'goldcalculator-42271.appspot.com',
    measurementId: 'G-S19SVR8N33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-WUjNKGgvcyrurUJJV6QTIY2UFY0hFc4',
    appId: '1:314765251666:android:4a44527af6c3c401947b8b',
    messagingSenderId: '314765251666',
    projectId: 'goldcalculator-42271',
    databaseURL: 'https://goldcalculator-42271.firebaseio.com',
    storageBucket: 'goldcalculator-42271.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsw2euoLQ1JVsTsMitm23jsz1lbQRdhTk',
    appId: '1:314765251666:ios:373ecd32e25c8960947b8b',
    messagingSenderId: '314765251666',
    projectId: 'goldcalculator-42271',
    databaseURL: 'https://goldcalculator-42271.firebaseio.com',
    storageBucket: 'goldcalculator-42271.appspot.com',
    androidClientId: '314765251666-0avd3lk3i6bn4eae24rrm6ie234kcnk3.apps.googleusercontent.com',
    iosClientId: '314765251666-3551oevuh9pu5u9usrpglfa7o77pqi31.apps.googleusercontent.com',
    iosBundleId: 'com.login.logingoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsw2euoLQ1JVsTsMitm23jsz1lbQRdhTk',
    appId: '1:314765251666:ios:df56159d7eb8f54a947b8b',
    messagingSenderId: '314765251666',
    projectId: 'goldcalculator-42271',
    databaseURL: 'https://goldcalculator-42271.firebaseio.com',
    storageBucket: 'goldcalculator-42271.appspot.com',
    androidClientId: '314765251666-0avd3lk3i6bn4eae24rrm6ie234kcnk3.apps.googleusercontent.com',
    iosClientId: '314765251666-eak84172r39a1pqr7jc8ni9ocq832ip0.apps.googleusercontent.com',
    iosBundleId: 'com.login.logingoogle.RunnerTests',
  );
}
